package com.argus.edge

import org.json.JSONObject
import kotlin.math.exp

/**
 * On-device exercise form classification — the phone half of `form_reason_codes`.
 *
 * The laptop's scorer never sees a pose well enough to judge form: it scores
 * fall, stillness, occlusion and orientation from keypoint *history*, and
 * takes form as a closed-vocabulary verdict this class produces. So this is
 * where an exercise is judged, and the only thing that crosses the wire is
 * which of `[scoring.form_error_vocab]`'s codes applies.
 *
 * One instance handles one exercise. `MainActivity` keeps a registry of
 * `exercise -> asset name` (see `openFormClassifiers()`) and loads one
 * instance per shipped artifact; this class itself is exercise-agnostic --
 * it reads landmarks, feature kinds, classes and the code mapping from the
 * artifact rather than assuming any of them, per docs/ADDING_AN_EXERCISE.md §3.
 *
 * ## Why there is no model runtime here
 *
 * The classifier is a multinomial logistic regression: standardize the
 * features, multiply by a CxN matrix, add an intercept, softmax. That is
 * arithmetic, so it runs in Kotlin directly — no ONNX session, no second NPU
 * dispatch on a path where dispatch alone costs ~500 us (android/README.md),
 * and no third artifact to stage on the device. The weights ship as
 * `assets/<exercise>_lr.json`, generated by `scripts/train_form_model.py`.
 *
 * ## Why the arithmetic is pinned
 *
 * This is a reimplementation of a model fitted in Python, which is exactly the
 * situation `DecodeTest` and `ProtocolTest` already exist for. The generator
 * also emits `tests/data/<exercise>_vectors.json` — real feature vectors with
 * the probabilities the fitted model produced — and `FormClassifierTest`
 * requires this code to reproduce them to 1e-6. A drift in feature order, in
 * the standardization, or in the softmax fails there rather than in a gym.
 *
 * ## Accuracy
 *
 * See docs/VALIDATION.md for the per-exercise figures and their caveats --
 * none of them is a claim about a new trainee, only about held-out frames
 * from the same few source recordings. Below [probabilityThreshold] this
 * class returns no codes at all rather than its best guess — the source
 * project's own "unknown" behaviour, and the right one, since an uncertain
 * verdict is not worth walking an instructor across a floor for.
 */
class FormClassifier private constructor(
    val exercise: String,
    private val landmarks: List<String>,
    private val featureKinds: List<String>,
    private val scalerMean: DoubleArray,
    private val scalerScale: DoubleArray,
    private val coef: Array<DoubleArray>,
    private val intercept: DoubleArray,
    private val classes: List<String>,
    private val classToCode: Map<String, String?>,
    private val minVisibleLandmarks: Int,
    private val depthGate: DepthGate?,
    val probabilityThreshold: Double,
    val encoding: String,
) {

    /** COCO-17 indices of the landmarks the model reads, in feature order. */
    private val cocoIndices: IntArray = landmarks.map { name ->
        COCO_NAMES.indexOf(name).also {
            require(it >= 0) { "artifact names a landmark COCO-17 does not have: $name" }
        }
    }.toIntArray()

    /**
     * A second evidence gate alongside landmark visibility, declared by the
     * artifact rather than hardcoded here. Lunge's `knee_over_toe` label was
     * only ever collected -- and, per upstream's own detection code, only
     * ever evaluated -- at the bottom of a lunge (see
     * `scripts/train_form_model.py` and docs/VALIDATION.md). A classifier
     * fitted on that has no idea what a standing or ascending trainee looks
     * like, and a softmax still confidently names one of its classes for one:
     * the same failure Trap 2 describes for plank, caused by pose rather than
     * occlusion. `min`/`max` are the training data's own observed range for
     * `mean(numerator_y) - mean(reference_y)`, in raw normalized-image
     * coordinates -- not a guessed threshold.
     */
    private data class DepthGate(
        val numeratorIndices: IntArray,
        val referenceIndices: IntArray,
        val min: Double,
        val max: Double,
    )

    /**
     * Classify one pose. Returns the `form_reason_codes` for the observation:
     * empty for correct form, empty when unconfident or ungated, one code
     * otherwise.
     *
     * `keypointsXy` is the protocol's 17 [x, y] pairs and `keypointsConf` its
     * 17 confidences — the same arrays [Observation.fromDetection] normalizes,
     * in the same COCO order.
     */
    fun classify(keypointsXy: FloatArray, keypointsConf: FloatArray): Verdict {
        require(keypointsXy.size == NUM_KEYPOINTS * 2 && keypointsConf.size == NUM_KEYPOINTS) {
            "expected COCO-17 keypoints, got ${keypointsXy.size / 2} points"
        }

        // Confidence gates the verdict; it is never a feature. See the note on
        // minVisibleLandmarks, and the module docstring of
        // scripts/train_form_model.py for what happened when it was one.
        val visible = cocoIndices.count { keypointsConf[it] >= MIN_LANDMARK_CONFIDENCE }
        if (visible < minVisibleLandmarks) {
            return unknownVerdict(visible)
        }

        val xs = DoubleArray(cocoIndices.size) { keypointsXy[cocoIndices[it] * 2].toDouble() }
        val ys = DoubleArray(cocoIndices.size) { keypointsXy[cocoIndices[it] * 2 + 1].toDouble() }

        depthGate?.let { gate ->
            val numerator = gate.numeratorIndices.map { ys[it] }.average()
            val reference = gate.referenceIndices.map { ys[it] }.average()
            val gap = numerator - reference
            if (gap < gate.min || gap > gate.max) return unknownVerdict(visible)
        }

        if (encoding == "bbox") normalizeToLandmarkBox(xs, ys)

        // Per-landmark, in the artifact's declared kind order — the same order
        // train_form_model.py builds feature_names in. Feature order is the
        // whole contract: a transposed layout still produces plausible
        // probabilities, which is why FormClassifierTest pins it.
        val features = DoubleArray(cocoIndices.size * featureKinds.size)
        for (i in cocoIndices.indices) {
            for ((k, kind) in featureKinds.withIndex()) {
                features[i * featureKinds.size + k] = when (kind) {
                    "x" -> xs[i]
                    "y" -> ys[i]
                    else -> throw IllegalStateException("artifact declares unknown feature kind '$kind'")
                }
            }
        }

        val probabilities = softmax(logits(features))
        var best = 0
        for (i in probabilities.indices) if (probabilities[i] > probabilities[best]) best = i

        val label = classes[best]
        val confident = probabilities[best] >= probabilityThreshold
        val code = if (confident) classToCode[label] else null
        return Verdict(
            exercise = exercise,
            label = label,
            probability = probabilities[best],
            confident = confident,
            formReasonCodes = if (code != null) listOf(code) else emptyList(),
            probabilities = probabilities,
            visibleLandmarks = visible,
            totalLandmarks = cocoIndices.size,
        )
    }

    private fun unknownVerdict(visible: Int): Verdict = Verdict(
        exercise = exercise,
        label = UNKNOWN,
        probability = 0.0,
        confident = false,
        formReasonCodes = emptyList(),
        probabilities = DoubleArray(classes.size),
        visibleLandmarks = visible,
        totalLandmarks = cocoIndices.size,
    )

    private fun logits(features: DoubleArray): DoubleArray = DoubleArray(classes.size) { c ->
        var sum = intercept[c]
        val row = coef[c]
        for (i in features.indices) {
            sum += row[i] * ((features[i] - scalerMean[i]) / scalerScale[i])
        }
        sum
    }

    /**
     * Softmax, shifted by the maximum logit.
     *
     * The shift is not a micro-optimisation: `exp` of an unshifted logit
     * overflows to infinity on a degenerate pose and the probabilities come
     * back NaN, which compares false against every threshold and would
     * silently mean "never report a form error".
     */
    private fun softmax(logits: DoubleArray): DoubleArray {
        val max = logits.max()
        val exps = DoubleArray(logits.size) { exp(logits[it] - max) }
        val total = exps.sum()
        return DoubleArray(exps.size) { exps[it] / total }
    }

    data class Verdict(
        val exercise: String,
        val label: String,
        val probability: Double,
        val confident: Boolean,
        val formReasonCodes: List<String>,
        val probabilities: DoubleArray,
        val visibleLandmarks: Int = 0,
        val totalLandmarks: Int = 0,
    ) {
        /** Human-readable, for the status strip. Never crosses the wire. */
        fun describe(): String = when {
            label == UNKNOWN -> "$exercise: not enough of the body visible ($visibleLandmarks/$totalLandmarks)"
            !confident -> "$exercise: unsure (${(probability * 100).toInt()}%)"
            formReasonCodes.isEmpty() -> "$exercise: correct (${(probability * 100).toInt()}%)"
            else -> "$exercise: ${formReasonCodes.first()} (${(probability * 100).toInt()}%)"
        }
    }

    companion object {
        /** COCO-17 names, index-aligned with the protocol's keypoint order. */
        val COCO_NAMES = listOf(
            "nose", "left_eye", "right_eye", "left_ear", "right_ear",
            "left_shoulder", "right_shoulder", "left_elbow", "right_elbow",
            "left_wrist", "right_wrist", "left_hip", "right_hip",
            "left_knee", "right_knee", "left_ankle", "right_ankle",
        )

        /** Label for "the phone cannot see enough to judge". Never a wire code. */
        const val UNKNOWN = "?"

        /**
         * Per-keypoint confidence at which a landmark counts as seen. Matches
         * the server's own `[scoring] keypoint_conf_threshold`, so both ends
         * agree on what "visible" means.
         */
        const val MIN_LANDMARK_CONFIDENCE = 0.3f

        fun fromJson(text: String): FormClassifier {
            val root = JSONObject(text)
            val format = root.getString("format")
            require(format == "multinomial_logistic_regression") {
                "unsupported form artifact format: $format"
            }

            val exercise = root.getString("exercise")
            val landmarks = root.getJSONArray("landmarks").let { a ->
                List(a.length()) { a.getString(it) }
            }
            val featureKinds = root.getJSONArray("feature_kinds").let { a ->
                List(a.length()) { a.getString(it) }
            }
            val classes = root.getJSONArray("classes").let { a ->
                List(a.length()) { a.getString(it) }
            }
            val codeMap = root.getJSONObject("class_to_code")
            val classToCode = classes.associateWith { c ->
                if (codeMap.isNull(c)) null else codeMap.getString(c)
            }

            val mean = root.getJSONArray("scaler_mean").toDoubleArray()
            val scale = root.getJSONArray("scaler_scale").toDoubleArray()
            val coefRaw = root.getJSONArray("coef")
            val coef = Array(coefRaw.length()) { coefRaw.getJSONArray(it).toDoubleArray() }
            val intercept = root.getJSONArray("intercept").toDoubleArray()

            require(featureKinds.isNotEmpty() && featureKinds.all { it == "x" || it == "y" }) {
                "artifact declares feature kinds $featureKinds; this build understands " +
                    "coordinates only. A confidence-valued feature is what made an " +
                    "earlier revision report 100% on whatever it was pointed at."
            }
            val expected = landmarks.size * featureKinds.size
            require(mean.size == expected && scale.size == expected) {
                "artifact scaler is ${mean.size} long, expected $expected for " +
                    "${landmarks.size} landmarks x ${featureKinds.size} kinds"
            }
            require(coef.size == classes.size && intercept.size == classes.size) {
                "artifact has ${coef.size} coefficient rows for ${classes.size} classes"
            }
            require(coef.all { it.size == expected }) {
                "artifact coefficient rows are not $expected wide"
            }
            require(scale.none { it == 0.0 }) {
                "artifact scaler has a zero scale; standardization would divide by zero"
            }

            val minVisibleLandmarks = root.getInt("min_visible_landmarks")
            require(minVisibleLandmarks in 1..landmarks.size) {
                "artifact min_visible_landmarks $minVisibleLandmarks is out of range for " +
                    "${landmarks.size} landmarks"
            }

            val depthGate = if (root.isNull("depth_gate")) null else {
                val g = root.getJSONObject("depth_gate")
                fun indices(key: String) = g.getJSONArray(key).let { a ->
                    IntArray(a.length()) { i ->
                        val name = a.getString(i)
                        landmarks.indexOf(name).also {
                            require(it >= 0) { "depth_gate names a landmark not in this artifact: $name" }
                        }
                    }
                }
                DepthGate(
                    numeratorIndices = indices("numerator_landmarks"),
                    referenceIndices = indices("reference_landmarks"),
                    min = g.getDouble("min"),
                    max = g.getDouble("max"),
                )
            }

            return FormClassifier(
                exercise = exercise,
                landmarks = landmarks,
                featureKinds = featureKinds,
                scalerMean = mean,
                scalerScale = scale,
                coef = coef,
                intercept = intercept,
                classes = classes,
                classToCode = classToCode,
                minVisibleLandmarks = minVisibleLandmarks,
                depthGate = depthGate,
                probabilityThreshold = root.getDouble("probability_threshold"),
                encoding = root.getString("encoding"),
            )
        }

        /**
         * Re-express coordinates relative to the box the model's landmarks
         * span — the same transform `train_form_model.bbox_normalize` applies,
         * and deliberately not the detector's `bbox_xyxy`: the model was fitted
         * against the landmark extent, and MediaPipe's person box and YOLO26's
         * are not the same convention.
         */
        internal fun normalizeToLandmarkBox(xs: DoubleArray, ys: DoubleArray) {
            val x0 = xs.min()
            val y0 = ys.min()
            val w = maxOf(xs.max() - x0, 1e-6)
            val h = maxOf(ys.max() - y0, 1e-6)
            for (i in xs.indices) {
                xs[i] = (xs[i] - x0) / w
                ys[i] = (ys[i] - y0) / h
            }
        }

        private fun org.json.JSONArray.toDoubleArray(): DoubleArray =
            DoubleArray(length()) { getDouble(it) }
    }
}
