package com.argus.edge

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * The phone half of the protocol contract (`docs/PROTOCOL.md`).
 *
 * `tests/data/protocol_vectors.json` is generated by the *server's* codebase
 * and every valid message in it is guaranteed to pass the server's parser.
 * This test asserts the Kotlin encoder reproduces those messages value-for-
 * value — key set and decoded values, not bytes, since the two languages
 * format doubles differently and the server parses rather than compares.
 */
class ProtocolTest {

    private val fixture: JSONObject by lazy {
        val dir = System.getProperty("argus.fixtures")
            ?: error("argus.fixtures system property not set")
        JSONObject(File(dir, "protocol_vectors.json").readText())
    }

    @Test
    fun `the encoder is on the fixture's protocol version`() {
        assertEquals(fixture.getInt("protocol_version"), PROTOCOL_VERSION)
    }

    @Test
    fun `hello messages match the canonical fixture`() {
        forEachValid("hello") { canonical ->
            val mine = JSONObject(
                encodeHello(
                    stationId = canonical.getString("station_id"),
                    traineeId = canonical.getString("trainee_id"),
                    exercisePlan = canonical.optString("exercise_plan", ""),
                )
            )
            assertJsonEquals(canonical, mine)
        }
    }

    @Test
    fun `observation messages match the canonical fixture`() {
        forEachValid("observation") { canonical ->
            val obs = Observation(
                ts = canonical.getDouble("ts"),
                bboxNorm = canonical.getJSONArray("bbox_xyxy").toDoubleList(),
                keypointsXy = canonical.getJSONArray("keypoints_xy").let { arr ->
                    List(arr.length()) { arr.getJSONArray(it).toDoubleList() }
                },
                keypointsConf = canonical.getJSONArray("keypoints_conf").toDoubleList(),
                exercise = if (canonical.has("exercise")) canonical.getString("exercise") else null,
                repCount = if (canonical.has("rep_count")) canonical.getInt("rep_count") else null,
                formOk = if (canonical.has("form_ok")) canonical.getBoolean("form_ok") else null,
                formReasonCodes = if (canonical.has("form_reason_codes"))
                    canonical.getJSONArray("form_reason_codes").let { a -> List(a.length()) { a.getString(it) } }
                else emptyList(),
            )
            val mine = JSONObject(encodeObservation(obs))
            // The canonical fixture may carry an explicit empty form_reason_codes;
            // the encoder omits the empty default. Both parse identically —
            // normalize before comparing.
            if (canonical.has("form_reason_codes") &&
                canonical.getJSONArray("form_reason_codes").length() == 0 &&
                !mine.has("form_reason_codes")
            ) {
                mine.put("form_reason_codes", JSONArray())
            }
            assertJsonEquals(canonical, mine)
        }
    }

    @Test
    fun `a phone with no pose model reports zero-confidence keypoints not fewer`() {
        val obs = Observation(ts = 1.0, bboxNorm = listOf(0.1, 0.1, 0.9, 0.9))
        val encoded = JSONObject(encodeObservation(obs))
        assertEquals(NUM_KEYPOINTS, encoded.getJSONArray("keypoints_xy").length())
        assertEquals(NUM_KEYPOINTS, encoded.getJSONArray("keypoints_conf").length())
    }

    @Test
    fun `out-of-range normalized coordinates are refused at construction`() {
        try {
            Observation(ts = 0.0, bboxNorm = listOf(0.0, 0.0, 1.5, 1.0))
            fail("a bbox outside [0,1] must not construct")
        } catch (expected: ProtocolException) { /* the contract held */ }
    }

    @Test
    fun `detection normalization clamps and divides by the frame`() {
        val obs = Observation.fromDetection(
            ts = 2.0, det = Detection(192f, 108f, 1920f, 1080f, 0.9f),
            frameWidth = 1920, frameHeight = 1080,
        )
        assertEquals(listOf(0.1, 0.1, 1.0, 1.0), obs.bboxNorm)
    }

    // -- helpers -------------------------------------------------------------

    private fun forEachValid(type: String, body: (JSONObject) -> Unit) {
        val valid = fixture.getJSONArray("valid")
        var seen = 0
        for (i in 0 until valid.length()) {
            val message = valid.getJSONObject(i).getJSONObject("message")
            if (message.getString("type") == type) { seen += 1; body(message) }
        }
        assertTrue("fixture has no $type cases", seen > 0)
    }

    private fun JSONArray.toDoubleList(): List<Double> = List(length()) { getDouble(it) }

    private fun assertJsonEquals(expected: JSONObject, actual: JSONObject, path: String = "$") {
        assertEquals("$path key set", expected.keySet(), actual.keySet())
        for (key in expected.keySet()) {
            val e = expected.get(key)
            val a = actual.get(key)
            when (e) {
                is JSONObject -> assertJsonEquals(e, a as JSONObject, "$path.$key")
                is JSONArray -> {
                    a as JSONArray
                    assertEquals("$path.$key length", e.length(), a.length())
                    for (i in 0 until e.length()) {
                        when (val ei = e.get(i)) {
                            is JSONArray -> {
                                val ai = a.getJSONArray(i)
                                assertEquals("$path.$key[$i] length", ei.length(), ai.length())
                                for (j in 0 until ei.length()) {
                                    assertEquals("$path.$key[$i][$j]", ei.getDouble(j), ai.getDouble(j), 0.0)
                                }
                            }
                            is Number -> assertEquals("$path.$key[$i]", e.getDouble(i), a.getDouble(i), 0.0)
                            else -> assertEquals("$path.$key[$i]", ei, a.get(i))
                        }
                    }
                }
                is Number -> assertEquals("$path.$key", expected.getDouble(key), actual.getDouble(key), 0.0)
                else -> assertEquals("$path.$key", e, a)
            }
        }
    }
}
