package com.argus.edge

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.nio.FloatBuffer

/**
 * Does the QNN execution provider actually place a graph on this phone's NPU?
 *
 * Everything else in this module can be checked on a laptop. This cannot, and it
 * is the single assumption the whole edge design rests on: that the Hexagon NPU
 * is reachable from an ordinary Android app, with the runtime Gradle packaged
 * and no Qualcomm SDK staged by hand.
 *
 * `docs/VALIDATION.md` §4 records that the PC's NPU path has never executed on
 * hardware, and §7 records the habit this project exists to break — shipping
 * plausible code that has never run. So this is deliberately an *instrumented*
 * test: it runs on the device, or it does not run at all. It cannot pass on a
 * build machine that has no NPU, which is what makes it worth anything.
 *
 * The model is a single quantised Conv, generated by the snippet recorded in
 * `android/README.md`. It is not a detector and is not meant to be: what is
 * under test is the runtime path, not a model's accuracy.
 *
 * CPU fallback is disabled. If the graph cannot go on the NPU, session creation
 * throws and this test fails, rather than quietly succeeding on CPU and
 * reporting a green tick for a capability the device may not have.
 */
@RunWith(AndroidJUnit4::class)
class QnnSessionTest {

    private val backend: File
        get() {
            val ctx = InstrumentationRegistry.getInstrumentation().targetContext
            return File(ctx.applicationInfo.nativeLibraryDir, "libQnnHtp.so")
        }

    private fun modelBytes(): ByteArray =
        InstrumentationRegistry.getInstrumentation().context.assets
            .open("qnn_smoke_w8a8.onnx").use { it.readBytes() }

    @Test
    fun theQnnBackendIsPackagedIntoTheApk() {
        assertTrue(
            "libQnnHtp.so missing from ${backend.parent} -- it should arrive " +
                "transitively via com.qualcomm.qti:qnn-runtime",
            backend.isFile,
        )
    }

    /**
     * Which QNN option sets this device actually accepts.
     *
     * Kept as a test rather than deleted after the fact: the first attempt here
     * failed with `QNN_DEVICE_ERROR_INVALID_CONFIG` on a config that the
     * documentation presents as ordinary, and the only way that was diagnosable
     * was by trying them side by side on the hardware. If a future runtime or a
     * different Hexagon version narrows what is accepted, this says so in one
     * run instead of one bisect.
     */
    @Test
    fun reportWhichQnnConfigurationsThisDeviceAccepts() {
        val env = OrtEnvironment.getEnvironment()
        val candidates = linkedMapOf(
            "backend_path only" to mapOf("backend_path" to backend.absolutePath),
            "+ burst" to mapOf(
                "backend_path" to backend.absolutePath,
                "htp_performance_mode" to "burst",
            ),
            "+ high_performance" to mapOf(
                "backend_path" to backend.absolutePath,
                "htp_performance_mode" to "high_performance",
            ),
            // The SM8750's Hexagon is v79. If the EP's own detection builds a
            // device config the runtime rejects, stating the arch explicitly is
            // the documented way round it.
            "+ htp_arch=79" to mapOf(
                "backend_path" to backend.absolutePath,
                "htp_arch" to "79",
            ),
            "+ htp_arch=79 device_id=0" to mapOf(
                "backend_path" to backend.absolutePath,
                "htp_arch" to "79",
                "device_id" to "0",
            ),
            "+ htp_arch=75 (deliberate mismatch)" to mapOf(
                "backend_path" to backend.absolutePath,
                "htp_arch" to "75",
            ),
            "+ fp16 precision" to mapOf(
                "backend_path" to backend.absolutePath,
                "htp_arch" to "79",
                "enable_htp_fp16_precision" to "1",
            ),
            // Control. The GPU backend goes through the same execution-provider
            // wiring but does not touch the DSP, so it separates "the EP is
            // misconfigured" from "this app cannot reach the Hexagon at all".
            "GPU backend (control)" to mapOf(
                "backend_path" to File(backend.parentFile, "libQnnGpu.so").absolutePath,
            ),
        )

        // The skel (libQnnHtpV79Skel.so) is loaded onto the DSP, not into this
        // process, and the DSP resolves it through ADSP_LIBRARY_PATH rather than
        // through the app's linker namespace. Unset, the device has nowhere to
        // find it -- which is a plausible reading of INVALID_CONFIG. Set before
        // any session is created, since QNN reads it when the backend comes up.
        android.system.Os.setenv("ADSP_LIBRARY_PATH", backend.parent, true)
        val outcome = StringBuilder()
        var anyWorked = false
        for ((label, config) in candidates) {
            val result = runCatching {
                val options = OrtSession.SessionOptions()
                options.addConfigEntry("session.disable_cpu_ep_fallback", "1")
                options.addQnn(config)
                env.createSession(modelBytes(), options).close()
            }
            anyWorked = anyWorked || result.isSuccess
            outcome.append("\n  ").append(if (result.isSuccess) "OK   " else "FAIL ")
                .append(label)
                .append(result.exceptionOrNull()?.let { " -- ${it.message?.take(140)}" } ?: "")
        }
        assertTrue("no QNN configuration placed the graph on the NPU:$outcome", anyWorked)
        println("QNN configuration support on this device:$outcome")
    }

    /**
     * The vendor-neutral route to the same accelerator.
     *
     * Direct QNN needs `/dev/fastrpc-cdsp`, which on a retail handset is
     * `system:system` under SELinux label `vendor_qdsp_device` with SELinux
     * enforcing — unreachable from `untrusted_app`, and unreachable even from
     * `shell`. NNAPI exists precisely to bridge that: the app hands the graph to
     * a system service, and the vendor HAL — which *does* have DSP access —
     * dispatches it to the NPU or DSP on the app's behalf.
     *
     * If this passes, the edge design survives on stock hardware and only the
     * mechanism changes. If it does not, on-device acceleration needs either a
     * platform-signed build or a developer device, which is a hardware and
     * procurement decision rather than a coding one.
     */
    @Test
    fun reportWhetherNnapiCanReachAnAccelerator() {
        val env = OrtEnvironment.getEnvironment()
        val report = StringBuilder()
        var worked = false

        for ((label, build) in listOf<Pair<String, (OrtSession.SessionOptions) -> Unit>>(
            "NNAPI (default)" to { o -> o.addNnapi() },
            "CPU baseline" to { _ -> },
        )) {
            val result = runCatching {
                val options = OrtSession.SessionOptions()
                build(options)
                env.createSession(modelBytes(), options).use { session ->
                    val input = FloatBuffer.allocate(1 * 3 * 32 * 32).apply {
                        repeat(capacity()) { put(0.5f) }; rewind()
                    }
                    OnnxTensor.createTensor(env, input, longArrayOf(1, 3, 32, 32)).use { t ->
                        session.run(mapOf("x" to t)).use { it[0].value as Array<*> }
                    }
                }
            }
            worked = worked || (label.startsWith("NNAPI") && result.isSuccess)
            report.append("\n  ").append(if (result.isSuccess) "OK   " else "FAIL ").append(label)
                .append(result.exceptionOrNull()?.let { " -- ${it.message?.take(120)}" } ?: "")
        }

        println("accelerator availability:$report")
        assertTrue("no execution path ran the graph at all:$report", report.contains("OK"))
    }

    @Test
    fun aGraphLoadsAndRunsOnTheNpuWithoutCpuFallback() {
        val env = OrtEnvironment.getEnvironment()
        val options = OrtSession.SessionOptions()
        // The whole point of the test: if QNN cannot take the graph, fail here
        // rather than silently running it on CPU.
        options.addConfigEntry("session.disable_cpu_ep_fallback", "1")
        options.addQnn(mapOf("backend_path" to backend.absolutePath))

        env.createSession(modelBytes(), options).use { session ->
            assertEquals(setOf("x"), session.inputNames.toSet())

            val input = FloatBuffer.allocate(1 * 3 * 32 * 32).apply {
                repeat(capacity()) { put(0.5f) }
                rewind()
            }
            OnnxTensor.createTensor(env, input, longArrayOf(1, 3, 32, 32)).use { tensor ->
                session.run(mapOf("x" to tensor)).use { result ->
                    val output = result[0].value as Array<*>
                    assertNotNull("the NPU produced no output", output)
                    assertEquals("unexpected batch dimension", 1, output.size)
                }
            }
        }
    }
}
